### ISSUE TITLE
Value of lines

### ISSUE THREAD

**Issue by ClaudiaDumitru** [alexandruradovici/alf-semantic-ast-public#2] opened 2017-04-25 20:59 UTC
Some of the tests have weird values for the line keys. For example, in the variable_list test, all the lines are set as 5, even though the variables are defined on different lines. In other tests, such as the ones for functions, the last line's value(for the script node) is the number of lines in the file + 1. Are those correct?

**Comment by alexandruradovici** [comment] 2017-04-25 22:11
The line number for the variable definitions was a bug, it should be fixed now.

For the functions and the script, the problem is in the way the jison is executing actions. yylineno is the line number where the parser is currently reading tokens when it executes the actions. This means the parser has parsed the rule. 

If the rule spreads on several lines, the last line is the value of yylineno.

A solution to this would be to add a rule for each keyword that is an instruction spreading on more than a line and put in it's action to return just the line number.

Here is a snippet. This would be a little overhead, so for this homework the line numbering is fine.

````
function_definition:		define IDENTIFIER parameters AS statement_posibilities
			{
				if (!util.isArray ($5)) $5 = [$5];
				$$ = {
					type: 'define_function',
					id: $2,
					parameters: $3,
					value_type: 'empty',
					statements: $5,
					line: $1
				};
			};

define: DEFINE { $$ = yylineno+1; };
````

**Closed as completed** 2017-04-25 22:12 UTC
Labels: bug
